name: Push To Public
on:
  pull_request:
    types: ['closed']
    branches: ['cleared']
  workflow_dispatch:
jobs:
  approved:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ref: 'cleared'
      - name: Push to public repo
        id: push_directory
        uses: isuthermography/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: .
          destination-github-username: 'isuthermography'
          destination-repository-name: 'spatialnde2'
          user-email: noreply@noreply
          target-branch: master
